#!/usr/bin/env python3
"""Generate static, source-backed service and resource pages for Eduforn."""
from __future__ import annotations

import html
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

ARTICLES = [
    {
        "slug": "canada-off-campus-work-hours", "title": "Can international students work in Canada while studying?",
        "desc": "Understand Canada’s current off-campus work rule, eligibility conditions and where to verify your study permit conditions.",
        "category": "CANADA · STUDENT WORK", "answer": "Eligible international students may work off campus up to 24 hours per week during regular academic sessions, and full-time during scheduled breaks, if they meet IRCC’s conditions. Your permit and personal situation matter; verify before working.",
        "body": ["Check that your study permit includes permission to work and that you meet IRCC’s eligibility criteria, including enrolment at an eligible designated learning institution and program.", "The 24-hour limit applies to off-campus work during regular academic sessions. Rules differ for on-campus work, scheduled breaks, co-op placements and other situations. Count hours across all off-campus jobs.", "Do not begin work until you are eligible and have the required Social Insurance Number. If your studies, enrolment or permit change, check how that affects your authorization."],
        "source": [("IRCC: Work off campus as an international student", "https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work/work-off-campus.html")], "faq": [("Is the 24-hour limit automatic?", "No. Students must meet the current eligibility conditions and follow the conditions printed on their permit.")], "country": "Canada"
    },
    {
        "slug": "us-f1-student-visa", "title": "US F-1 student visa: steps after getting accepted",
        "desc": "A practical overview of the U.S. F-1 student visa sequence, from school certification to interview preparation.",
        "category": "UNITED STATES · STUDENT VISA", "answer": "After admission, an F-1 applicant generally needs a place at an SEVP-certified school, Form I-20, the required SEVIS fee payment, a DS-160 application and a visa interview. Follow the U.S. government instructions for your location and case.",
        "body": ["Confirm that the school is authorized to enroll international students and request your Form I-20 after meeting the school’s requirements. Review the form carefully and ask the school to correct any errors.", "Use the current Department of State instructions to complete the DS-160, pay required fees and book an interview where required. Prepare evidence that addresses the questions on the official student-visa guidance; document requirements can vary.", "A visa does not guarantee admission at the border, and admission to a school does not guarantee visa issuance. The consular officer decides the application. Never rely on a third party to promise an outcome."],
        "source": [("U.S. Department of State: Student Visa", "https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html"), ("Study in the States: School search", "https://studyinthestates.dhs.gov/school-search")], "faq": [("Does admission guarantee an F-1 visa?", "No. The U.S. government makes the visa decision after considering the individual application.")], "country": "United States"
    },
    {
        "slug": "uk-student-visa-checklist", "title": "UK Student visa checklist: documents and application basics",
        "desc": "Review the main UK Student visa preparation steps and check the current official document rules before applying.",
        "category": "UNITED KINGDOM · STUDENT VISA", "answer": "Most applicants need a Confirmation of Acceptance for Studies from a licensed student sponsor, a valid passport and evidence required for their situation. Additional financial, language, consent or health documents may apply. Check GOV.UK for your exact case.",
        "body": ["Start with the CAS issued by your education provider and make sure the course and personal details are correct. Apply within the permitted window and use the current GOV.UK application process.", "Check whether you must show funds, English-language evidence, an ATAS certificate, parental consent or other documents. The evidence rules depend on circumstances and can change; use the official checklist, not an old online template.", "Prepare clear copies and translations where required. Keep application references and follow the official instructions for biometrics and any requested follow-up."],
        "source": [("GOV.UK: Student visa documents", "https://www.gov.uk/student-visa/documents-you-must-provide"), ("GOV.UK: Student visa", "https://www.gov.uk/student-visa")], "faq": [("Can I use a generic checklist?", "Use it only as a planning aid. GOV.UK’s requirements for your circumstances are authoritative.")], "country": "United Kingdom"
    },
    {
        "slug": "australia-subclass-500", "title": "Australia Subclass 500 student visa: what to prepare",
        "desc": "Learn the core preparation points for an Australian Student visa (subclass 500) application and verify current requirements.",
        "category": "AUSTRALIA · STUDENT VISA", "answer": "A Student visa (subclass 500) application is tied to an eligible course and Confirmation of Enrolment. Applicants should check current document, health, character, English and Genuine Student requirements that apply to their individual case.",
        "body": ["Confirm the course and provider, receive your Confirmation of Enrolment, and review the Department of Home Affairs document checklist for your passport country and circumstances.", "Prepare evidence requested for your application, which may include identity, funds, English ability, health and character information. The Genuine Student questions ask you to explain your circumstances and study intentions truthfully.", "Lodge through the official system and monitor messages for additional requests. Visa conditions and work rights depend on current law and the visa granted; read the official conditions rather than relying on general summaries."],
        "source": [("Australian Department of Home Affairs: Student visa (subclass 500)", "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500")], "faq": [("Does every student submit identical evidence?", "No. Check the document checklist and instructions generated for your own application.")], "country": "Australia"
    },
    {
        "slug": "new-zealand-fee-paying-student-visa", "title": "New Zealand Fee Paying Student Visa: eligibility and evidence",
        "desc": "A starting guide to New Zealand’s Fee Paying Student Visa, including offer-of-place and evidence checks.",
        "category": "NEW ZEALAND · STUDENT VISA", "answer": "The Fee Paying Student Visa is for eligible students paying fees to study in New Zealand. Applicants generally need an offer of place from an approved provider and must meet current identity, funds, health and character requirements.",
        "body": ["Confirm the course and provider and obtain an offer of place that meets Immigration New Zealand’s requirements. Check the visa page for age, duration, fees and application timing that apply to you.", "Prepare evidence of tuition payment or ability to pay, living costs and onward travel as required. Health, character and insurance rules may also apply, depending on your stay and circumstances.", "Apply using the official online process and respond promptly to requests. Work rights, if granted, are subject to visa conditions; check the eVisa and official guidance."],
        "source": [("Immigration New Zealand: Fee Paying Student Visa", "https://www.immigration.govt.nz/visas/fee-paying-student-visa/")], "faq": [("Can I work on this visa?", "Some students may have work conditions. Check the specific visa conditions and current official rules.")], "country": "New Zealand"
    },
    {
        "slug": "ireland-long-stay-study-visa", "title": "Ireland long-stay study visa: application preparation",
        "desc": "Understand the official steps and documents for planning an Irish long-stay study visa application.",
        "category": "IRELAND · STUDY VISA", "answer": "Students planning a course longer than 90 days may need a long-stay study visa depending on nationality. Ireland’s immigration service lists the online application and supporting evidence requirements; check the latest rules for your case.",
        "body": ["Check whether your nationality requires a visa and whether your chosen course/provider meets current immigration requirements. Begin with the official long-stay study visa instructions and the course list where applicable.", "Complete the online application, follow the summary sheet instructions, and prepare the required evidence. This can include acceptance, fees, finances, academic history, English ability, insurance and explanations of any gaps, as specified by the current guidance.", "A visa is not a residence permission by itself for every step of a long stay. Follow instructions after arrival and check registration requirements and deadlines with Irish Immigration."],
        "source": [("Irish Immigration: Apply for a long-term study visa", "https://www.irishimmigration.ie/coming-to-study-in-ireland/what-are-my-study-visa-options/how-to-apply-for-long-term-study-visa/"), ("Irish Immigration: Study visa options", "https://www.irishimmigration.ie/coming-to-study-in-ireland/")], "faq": [("Do all students need a visa?", "Visa need depends on nationality and length/purpose of stay. Use Irish Immigration’s current guidance.")], "country": "Ireland"
    },
    {
        "slug": "singapore-students-pass", "title": "Singapore Student’s Pass: who needs one and how to apply",
        "desc": "Find out when international students need a Singapore Student’s Pass and how to verify the application sequence.",
        "category": "SINGAPORE · STUDENT PASS", "answer": "Foreign students accepted for full-time study at an eligible Singapore institution generally need a Student’s Pass unless an exemption applies. The institution and ICA’s current instructions guide the application sequence and timing.",
        "body": ["Confirm that the course is full-time and the institution is eligible to sponsor or support the Student’s Pass application. Part-time, evening or weekend courses may be treated differently.", "Follow the institution’s instructions to begin the application through the official system, submit accurate identity and supporting documents, and meet the stated deadlines. Processing steps and required documents can vary.", "Do not assume a visit pass is equivalent to a Student’s Pass. Check the approval and issuance steps, any medical requirements, and the conditions attached to your pass before travelling or starting classes."],
        "source": [("Immigration & Checkpoints Authority of Singapore: Student’s Pass application", "https://www.ica.gov.sg/reside/STP/apply")], "faq": [("Can I study on a tourist visit?", "Do not assume so. Check the pass required for your course and circumstances with ICA and your institution.")], "country": "Singapore"
    },
    {
        "slug": "study-in-dubai-student-visa", "title": "Study in Dubai: student residence visa routes to understand",
        "desc": "An introductory guide to student residence arrangements in the UAE; confirm sponsoring route and current rules with official authorities.",
        "category": "UAE · STUDENT RESIDENCE", "answer": "International students in the UAE may be sponsored for residence through an eligible university, parent or other permitted sponsor, subject to current UAE rules. The exact route depends on the institution, emirate and applicant’s circumstances.",
        "body": ["Ask the institution which residence route it supports and what admission, identity, medical, insurance or financial documents it requires. Procedures can differ by emirate and sponsor.", "Use the UAE government and relevant emirate authority guidance to confirm eligibility, validity, renewal, fees and any conditions. Do not rely on a university marketing page alone for immigration decisions.", "Check how residence status relates to arrival, study start dates and any work permission. Visa or residence decisions belong to the relevant UAE authorities."],
        "source": [("UAE Government: Residence visa for studying in the UAE", "https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/residence-visa-for-studying-in-the-uae")], "faq": [("Does the same student visa process apply across the UAE?", "Not necessarily. Verify the sponsoring institution and applicable emirate authority requirements.")], "country": "Dubai / UAE"
    },
    {
        "slug": "study-in-europe-country-comparison", "title": "Study in Europe: compare countries, courses and funding",
        "desc": "A practical framework for comparing European study destinations, course language, costs, funding and national visa rules.",
        "category": "EUROPE · DESTINATION PLANNING", "answer": "Europe is not one admissions or visa system. Compare countries and institutions individually, then confirm course, tuition, language, scholarship and immigration requirements through the provider and national authorities.",
        "body": ["Start with subject fit and language of instruction. Check the course page for entry requirements, qualification recognition, teaching language, calendar and whether the institution is officially recognized in that country.", "Build a realistic budget that includes tuition, housing, insurance, transport and application costs. Search official scholarship portals and institution funding pages; eligibility and deadlines vary.", "After choosing a country, check its national immigration authority for student visa or residence requirements. The European Union’s study portal is a discovery resource, not a substitute for national rules."],
        "source": [("European Commission: Study in Europe", "https://education.ec.europa.eu/study-in-europe"), ("European Commission: Scholarships and funding", "https://education.ec.europa.eu/study-in-europe/planning-your-studies/scholarships-and-funding")], "faq": [("Is there one student visa for all of Europe?", "No. Immigration requirements are set by individual countries; verify with the destination country’s authority.")], "country": "Europe"
    },
    {
        "slug": "study-abroad-scholarships-education-loans", "title": "Study abroad scholarships and education loans: research safely",
        "desc": "A safe checklist for researching study abroad scholarships, education loans and funding claims.",
        "category": "FUNDING · SCHOLARSHIPS", "answer": "Start with official university, government and recognized lender sources. Compare eligibility, total cost, repayment terms and deadlines, and never pay an unverified agent a fee to “secure” a scholarship or guaranteed loan.",
        "body": ["Search the destination government, institution and recognized scholarship-provider pages. Record eligibility, covered costs, renewal rules, application materials and deadlines. Scholarships can be competitive and may cover only part of the cost.", "For loans, compare the annual percentage rate or equivalent, fees, currency, collateral or co-signer requirements, repayment start date, moratorium, exchange-rate exposure and early-payment terms. Ask the lender for a written schedule.", "Verify the recipient domain and contact the institution using details from its official website. Treat guaranteed awards, urgency, advance payment demands and requests for passwords or one-time codes as warning signs."],
        "source": [("European Commission: Scholarships and funding", "https://education.ec.europa.eu/study-in-europe/planning-your-studies/scholarships-and-funding"), ("RBI: Sachet portal for reporting financial fraud", "https://sachet.rbi.org.in/")], "faq": [("Can an adviser guarantee a scholarship or loan?", "No. Awards are made by scholarship providers and loans are subject to lender approval and terms.")], "country": "All destinations"
    },
    {
        "slug": "selt-english-test-booking", "title": "Skills for English SELT: what to check before booking",
        "desc": "Check test type, approved provider, location, score and validity rules before booking a Skills for English SELT.",
        "category": "ENGLISH TESTS · SELT", "answer": "A SELT is a Secure English Language Test accepted for specified UK immigration routes when the test, level, provider and location meet current UK requirements. Verify the exact route and approved test list before booking.",
        "body": ["First check the requirement for your intended visa or institution. A test accepted for admission may not meet an immigration SELT rule, and a SELT requirement may specify a particular level or test format.", "Use the UK government’s approved test provider list and confirm the exact test, delivery location and booking procedure. Check identification rules, result timelines, cancellation terms and score validity before paying.", "If Eduforn offers preparation, confirm class format, fees, dates and whether it is separate from test booking. Training does not guarantee a score or visa outcome."],
        "source": [("GOV.UK: Approved Secure English Language Tests", "https://www.gov.uk/guidance/prove-your-english-language-abilities-with-a-secure-english-language-test-selt")], "faq": [("Is every English test accepted as a SELT?", "No. Check that the exact test and provider are approved for your immigration route.")], "country": "United Kingdom"
    }
]

SERVICES = [
    ("career-study-counselling", "Career and study counselling", "Discuss interests, academic background, goals and budget to shape a study plan.", "Bring your academic history, goals, budget range and preferred intake. A counselling conversation can help you identify questions and possible next steps; it cannot guarantee admission or a visa."),
    ("test-preparation", "English and language test preparation", "Eduforn lists IELTS, PTE, SELT preparation and German language training.", "Before enrolling, confirm the current course, trainers, format, schedule, fees and included practice materials directly with Eduforn. Check the test required by your institution or visa route before booking an exam."),
    ("course-institution-guidance", "Course and institution guidance", "Compare study options and admissions information against your goals and profile.", "Shortlist by subject fit, entry requirements, location, total cost, course length, language and student support. Confirm current details with each institution; the provider decides admission and eligibility."),
    ("application-support", "Application support", "Get help understanding application steps, documents and timelines for your shortlist.", "Ask what the service includes, who submits each application, what fees are charged and how your documents are handled. Review all forms for accuracy before submission; applicants remain responsible for truthful information."),
    ("visa-guidance", "Visa guidance", "Understand the document-preparation process and where to find current official requirements.", "Visa rules change and depend on individual circumstances. Use the relevant government authority as the source of truth. Eduforn is not a government decision-maker and no adviser can guarantee an approval."),
    ("pre-departure-support", "Pre-departure support", "Plan practical next steps before travel and the start of your studies.", "Confirm what sessions or checklists are currently offered. Independently verify travel documents, accommodation, insurance, arrival instructions and institution orientation details before departure."),
    ("study-finance-guidance", "Study finance guidance", "Explore education funding questions and compare options carefully.", "Review the lender’s written terms, fees, interest, repayment schedule, currency exposure and collateral conditions. Confirm Eduforn’s role and any service fees directly. Loan approval belongs to the lender."),
    ("remittance-forex", "Remittance and forex", "Eduforn’s public website describes student-focused remittance and foreign exchange support.", "Verify the authorized provider, applicable exchange rate, fees, transfer limits, delivery timing, refund policy and identity requirements before sending money. Never share banking passwords or one-time codes."),
]

def esc(text: str) -> str:
    return html.escape(text, quote=True)

def shell(title: str, description: str, canonical_path: str, content: str, crumb: str) -> str:
    breadcrumb = f'<a href="{canonical_path}">{esc(crumb)}</a><span aria-hidden="true">/</span>' if canonical_path != "/" else ""
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#10172a"><meta name="description" content="{esc(description)}"><title>{esc(title)} | Eduforn</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/enhancements.css"><script src="/main.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to content</a><div class="topbar"><div class="container topbar-inner"><span>Student first guidance since 2015</span><div><a href="mailto:enquiry@eduforn.com">enquiry@eduforn.com</a><span class="topbar-dot">·</span><a href="tel:+918588851085">+91 85888 51085</a></div></div></div><header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="Eduforn home"><img src="/assets/eduforn-logo.webp" alt="Eduforn — Makes Your Travel Smooth"></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav"><span class="sr-only">Open navigation</span><i></i><i></i><i></i></button><nav class="primary-nav" id="primary-nav" aria-label="Main navigation"><a href="/">Home</a><a href="/destinations/">Destinations</a><a href="/services/">Services</a><a href="/course-finder/">Course finder</a><a href="/resource-corner/">Resource corner</a><a href="/about/">About</a><a class="button button-small" href="/contact/">Book free counselling <span aria-hidden="true">↗</span></a></nav></div></header><main id="main"><div class="container breadcrumbs"><a href="/">Home</a><span aria-hidden="true">/</span>{breadcrumb}<span aria-current="page">{esc(title)}</span></div>{content}</main>
<footer class="site-footer"><div class="container footer-main"><div class="footer-brand"><a href="/" aria-label="Eduforn home"><img src="/assets/eduforn-logo.webp" alt="Eduforn — Makes Your Travel Smooth"></a><p>Practical, student-first overseas education guidance.</p></div><div class="footer-destinations"><h3>Explore</h3><a href="/study-in-canada/">Canada</a><a href="/study-in-usa/">United States</a><a href="/study-in-uk/">United Kingdom</a><a href="/study-in-australia/">Australia</a><a href="/study-in-ireland/">Ireland</a><a href="/study-in-new-zealand/">New Zealand</a><a href="/study-in-dubai/">Dubai</a><a href="/study-in-singapore/">Singapore</a><a href="/study-in-europe/">Europe</a></div><div><h3>Get in touch</h3><a href="tel:+918588851085">+91 85888 51085</a><a href="mailto:enquiry@eduforn.com">enquiry@eduforn.com</a><a href="mailto:info@eduforn.com">info@eduforn.com</a><a href="/contact/">Contact options</a></div><div class="footer-cta"><p>Make the next step clearer.</p><a class="button button-light" href="/contact/">Book free counselling <span aria-hidden="true">↗</span></a></div></div><div class="container footer-bottom"><span>© 2026 Eduforn Overseas Pvt. Ltd.</span><span>Local redesign preview · Enquiries are not connected</span></div></footer></body></html>'''

def write_page(folder: str, title: str, desc: str, canonical: str, body: str, crumb: str) -> None:
    path = ROOT / folder / "index.html"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(shell(title, desc, canonical, body, crumb), encoding="utf-8")

def gen_articles() -> None:
    for item in ARTICLES:
        sources = "".join(f'<li><a href="{esc(url)}" target="_blank" rel="noopener noreferrer">{esc(label)}</a></li>' for label, url in item["source"])
        paragraphs = "".join(f"<p>{esc(p)}</p>" for p in item["body"])
        faqs = "".join(f"<h3>{esc(q)}</h3><p>{esc(a)}</p>" for q, a in item["faq"])
        content = f'''<article class="resource-article"><header class="article-header"><p class="eyebrow">{esc(item['category'])}</p><h1>{esc(item['title'])}</h1><p class="article-deck">{esc(item['desc'])}</p><div class="article-meta"><span>Eduforn Resource Corner</span><span>Official sources checked October 2026</span></div></header><div class="article-body"><h2>Short answer</h2><p>{esc(item['answer'])}</p><h2>What to check</h2>{paragraphs}<h2>Common question</h2>{faqs}<h2>Official sources</h2><ul class="article-sources">{sources}</ul><p class="article-disclaimer">This guide is general planning information, not legal or immigration advice. Requirements can change and depend on your circumstances. Confirm current details with official authorities and your chosen institution.</p></div><aside class="article-cta"><div><p class="eyebrow">PLAN YOUR NEXT STEP</p><h2>Need help comparing your options?</h2><p>Eduforn can discuss study planning and available support. Government authorities and institutions make their own decisions.</p></div><a class="button" href="/contact/">Talk to a counsellor <span aria-hidden="true">↗</span></a></aside></article>'''
        write_page(f"resource-corner/articles/{item['slug']}", item["title"], item["desc"], "/resource-corner/", content, "Resource Corner")

def gen_services() -> None:
    for slug, title, desc, detail in SERVICES:
        body = f'''<section class="resource-hero"><div class="container"><p class="eyebrow">EDUFORN SERVICE</p><h1>{esc(title)}</h1><p>{esc(desc)}</p><p>{esc(detail)}</p><div class="hero-actions"><a class="button" href="/contact/">Ask about this service <span aria-hidden="true">↗</span></a><a class="text-link" href="/services/">View all services <span aria-hidden="true">↗</span></a></div></div></section><section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">BEFORE YOU DECIDE</p><h2>Questions to <span>confirm directly.</span></h2></div></div><ul class="article-sources"><li>Is this service currently available for your destination and intake?</li><li>What is included, what does it cost, and what happens next?</li><li>Which decisions remain with the university, lender or government authority?</li></ul><p class="content-note">This page summarizes information published by Eduforn and is not a service agreement. Confirm availability, scope, terms and fees directly before proceeding.</p><a class="button button-outline" href="/study-abroad-consultants-in-new-delhi/">Find New Delhi contact details <span aria-hidden="true">↗</span></a></div></section>'''
        write_page(f"services/{slug}", title, desc, "/services/", body, "Services")

def gen_corporate_pages() -> None:
    pages = {
        "about": ("About Eduforn", "Learn about Eduforn’s overseas education guidance, published services and how to verify details before choosing support.", '''<section class="resource-hero"><div class="container"><p class="eyebrow">ABOUT EDUFORN</p><h1>Study abroad guidance, <span>built around your next step.</span></h1><p>Eduforn Overseas Pvt. Ltd. presents counselling and related support for students exploring international education. This redesign brings destinations, course discovery, services and official-source guidance together in one place.</p></div></section><section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">WHAT WE CAN VERIFY</p><h2>Clear information. <span>Thoughtful decisions.</span></h2></div></div><p class="body-copy">Eduforn’s current website describes services including education counselling, test preparation, applications, visa guidance and pre-departure support. Confirm current availability, terms and fees directly. Institution admission and immigration decisions are made by the relevant organizations.</p><p class="body-copy">Our preview keeps staff profiles marked as placeholders and student stories unpublished until real details and permission are confirmed. We do not publish unverified outcomes, credentials, partnerships or success-rate claims.</p><a class="button" href="/services/">Review available services <span aria-hidden="true">↗</span></a></div></section>'''),
        "how-it-works": ("How Study Abroad Planning Works", "A clear four-step study abroad planning process: understand your goals, shortlist courses, prepare applications and plan your next steps.", '''<section class="resource-hero"><div class="container"><p class="eyebrow">HOW IT WORKS</p><h1>Four steps. <span>One confident start.</span></h1><p>A practical framework for organizing a study abroad plan. Your exact requirements depend on the course, institution, destination and individual profile.</p></div></section><section class="section"><div class="container journey-steps"><article><span class="step-no">01</span><h2>Understand</h2><p>Gather your goals, education history, budget range and preferred timeline.</p></article><article><span class="step-no">02</span><h2>Shortlist</h2><p>Compare destinations, courses, institutions, entry criteria and total costs.</p></article><article><span class="step-no">03</span><h2>Prepare</h2><p>Use the institution’s current instructions to organize applications and documents.</p></article><article><span class="step-no">04</span><h2>Move forward</h2><p>Verify official visa and travel requirements and plan around confirmed deadlines.</p></article><p class="content-note">An adviser can help explain steps, but institutions, lenders and governments make their own decisions. No admission, funding or visa outcome is guaranteed.</p><a class="button" href="/contact/">Discuss your plans <span aria-hidden="true">↗</span></a></div></section>'''),
        "destinations": ("Study Abroad Destinations", "Explore Eduforn destination guides for Canada, the United States, the United Kingdom, Australia, Ireland, New Zealand, Dubai, Singapore and Europe.", '''<section class="resource-hero"><div class="container"><p class="eyebrow">EXPLORE DESTINATIONS</p><h1>Compare places to <span>study abroad.</span></h1><p>Choose a destination to explore study pathways, planning questions and official links. Course availability and immigration requirements must be confirmed with institutions and government sources.</p></div></section><section class="section destinations"><div class="container destination-grid"><a class="destination-card" href="/study-in-canada/"><div class="destination-flag"><img src="https://flagcdn.com/w160/ca.png" alt="Canada flag" loading="lazy"></div><h2>Canada</h2><p>Courses, institutions and study permit planning.</p></a><a class="destination-card" href="/study-in-usa/"><div class="destination-flag"><img src="https://flagcdn.com/w160/us.png" alt="United States flag" loading="lazy"></div><h2>United States</h2><p>Explore degree options and institutions.</p></a><a class="destination-card" href="/study-in-uk/"><div class="destination-flag"><img src="https://flagcdn.com/w160/gb.png" alt="United Kingdom flag" loading="lazy"></div><h2>United Kingdom</h2><p>Compare courses and plan your next step.</p></a><a class="destination-card" href="/study-in-australia/"><div class="destination-flag"><img src="https://flagcdn.com/w160/au.png" alt="Australia flag" loading="lazy"></div><h2>Australia</h2><p>Find a study path that matches your goals.</p></a><a class="destination-card" href="/study-in-ireland/"><div class="destination-flag"><img src="https://flagcdn.com/w160/ie.png" alt="Ireland flag" loading="lazy"></div><h2>Ireland</h2><p>Explore institutions and courses.</p></a><a class="destination-card" href="/study-in-new-zealand/"><div class="destination-flag"><img src="https://flagcdn.com/w160/nz.png" alt="New Zealand flag" loading="lazy"></div><h2>New Zealand</h2><p>Compare providers and pathways.</p></a><a class="destination-card" href="/study-in-dubai/"><div class="destination-flag"><img src="https://flagcdn.com/w160/ae.png" alt="United Arab Emirates flag" loading="lazy"></div><h2>Dubai</h2><p>Explore study options in the UAE.</p></a><a class="destination-card" href="/study-in-singapore/"><div class="destination-flag"><img src="https://flagcdn.com/w160/sg.png" alt="Singapore flag" loading="lazy"></div><h2>Singapore</h2><p>Explore universities and programs.</p></a><a class="destination-card" href="/study-in-europe/"><div class="destination-flag"><img src="https://flagcdn.com/w160/eu.png" alt="European Union flag" loading="lazy"></div><h2>Europe</h2><p>Explore options across European countries.</p></a></div></section>'''),
        "student-stories": ("Student Stories", "Read Eduforn student stories only when details have been verified and students have given informed permission.", '''<section class="resource-hero"><div class="container"><p class="eyebrow">STUDENT STORIES</p><h1>Real experiences, <span>shared with care.</span></h1><p>Student journeys can help others understand the process, but details belong to the students who lived them.</p></div></section><section class="section"><div class="container"><div class="story-consent-panel"><span class="story-consent-mark" aria-hidden="true">♡</span><div><b>No verified stories are published in this preview.</b><p>Eduforn should add a story only after checking facts and receiving the student’s clear permission for the exact name, image, quotation and outcome shown. Admission or visa results are individual and do not predict another person’s result.</p></div></div><p class="content-note">This local testing page contains no invented testimonials, student outcomes or case studies.</p><a class="button" href="/contact/">Ask about Eduforn’s support <span aria-hidden="true">↗</span></a></div></section>'''),
        "contact": ("Contact Eduforn", "Contact Eduforn about study abroad counselling. This local redesign form is a preview and does not send or store enquiries.", '''<section class="resource-hero"><div class="container"><p class="eyebrow">CONTACT EDUFORN</p><h1>Let’s talk about <span>your study plans.</span></h1><p>Use the published contact details to reach Eduforn. The enquiry form below is a local preview only and does not submit or store information.</p><div class="hero-actions"><a class="button" href="tel:+918588851085">Call +91 85888 51085</a><a class="text-link" href="mailto:enquiry@eduforn.com">Email Eduforn <span aria-hidden="true">↗</span></a></div></div></section><section class="section"><div class="container"><h2>New Delhi office</h2><address>136, First Floor, Avtar Enclave,<br>Paschim Vihar, New Delhi 110063</address><p><a href="tel:+919899387733">+91 98993 87733</a> · <a href="mailto:info@eduforn.com">info@eduforn.com</a></p><p class="content-note">Address, secondary phone and email are listed on Eduforn’s public contact page. Call ahead to confirm office hours and appointment availability.</p><h2>Local enquiry form preview</h2><p>For testing only. Do not enter sensitive personal or immigration information. No form data is sent to Eduforn or stored by this page.</p><form class="enquiry-form local-form"><div class="form-head"><div><span class="form-kicker">LOCAL PREVIEW</span><h3>Let’s talk about your plans.</h3></div></div><label>Full name<input name="name" autocomplete="name" placeholder="Your name" required></label><label>Phone number<input name="phone" type="tel" autocomplete="tel" placeholder="+91" required></label><label>Email address<input name="email" type="email" autocomplete="email" placeholder="you@example.com" required></label><label>Where are you thinking of studying?<select name="destination" required><option value="">Choose a destination</option><option>Canada</option><option>United States</option><option>United Kingdom</option><option>Ireland</option><option>Australia</option><option>New Zealand</option><option>Dubai</option><option>Singapore</option><option>Europe</option><option>Still exploring</option></select></label><label class="consent-row"><input type="checkbox" required><span>I agree to be contacted about my enquiry.</span></label><button class="button form-submit" type="submit">Request a callback <span aria-hidden="true">↗</span></button><p class="form-response" aria-live="polite">Local preview only: this form is not connected to Eduforn’s enquiry system.</p></form></div></section>'''),
        "privacy": ("Privacy Notice Draft", "Draft privacy notice for the Eduforn local redesign preview. Company review is required before publication.", '''<section class="resource-hero"><div class="container"><p class="eyebrow">DRAFT · BUSINESS REVIEW REQUIRED</p><h1>Privacy notice <span>for this preview.</span></h1><p>This is a working draft for review by Eduforn. It is not a final privacy policy or legal advice.</p></div></section><section class="section"><div class="container article-body"><h2>Local testing form</h2><p>The form in this preview is client-side only. Its submit handler prevents submission and displays a local message; it is not connected to an enquiry service. Do not enter sensitive personal, financial or immigration information.</p><h2>Contacting Eduforn</h2><p>If you choose to call or email Eduforn, your communication is handled through those channels and their providers. Confirm Eduforn’s actual data handling, retention, access and rights process before publishing a final notice.</p><h2>Hosting and site analytics</h2><p>Before production, Eduforn should confirm the hosting provider’s logs, any analytics or cookies, processors, retention periods and contact for privacy requests. This preview does not claim that these matters have been legally reviewed.</p><h2>Company review checklist</h2><ul><li>Confirm controller identity and privacy contact.</li><li>Describe the actual enquiry workflow and lawful basis.</li><li>Document retention, security, service providers and cross-border transfers.</li><li>Explain applicable user rights and complaint channels.</li></ul><p class="content-note">Do not treat this draft as a published compliance statement.</p></div></section>'''),
        "terms": ("Terms of Use Draft", "Draft terms of use for the Eduforn local redesign preview. Eduforn must review and finalize before publication.", '''<section class="resource-hero"><div class="container"><p class="eyebrow">DRAFT · BUSINESS REVIEW REQUIRED</p><h1>Terms of use <span>for this preview.</span></h1><p>This draft describes the intended informational nature of the redesign and requires Eduforn’s review before publication.</p></div></section><section class="section"><div class="container article-body"><h2>Informational content</h2><p>Destination, course and immigration information is a starting point, may become outdated and is not legal, immigration, financial or admissions advice. Verify details with the relevant institution, lender and official government source.</p><h2>No guaranteed outcomes</h2><p>Admission, visa, scholarship and loan decisions are made by independent institutions and authorities. No outcome is guaranteed by this preview.</p><h2>Preview limitations</h2><p>The enquiry form is not connected and should not be used to transmit personal information. Placeholder counsellor profiles and sample content must not be presented as verified Eduforn personnel or student results.</p><h2>Company review required</h2><p>Eduforn should confirm ownership, acceptable use, third-party links, liability language, governing law, dispute process and effective date with qualified reviewers before publishing final terms.</p><p class="content-note">This is not a legal contract and must be finalized by Eduforn.</p></div></section>''')
    }
    for slug, (title, desc, body) in pages.items():
        write_page(slug, title, desc, "/", body, "Home")
        if slug in {"privacy", "terms"}:
            path = ROOT / slug / "index.html"
            source = path.read_text(encoding="utf-8")
            source = source.replace("<meta name=\"description\"", "<meta name=\"robots\" content=\"noindex,follow\"><meta name=\"description\"", 1)
            path.write_text(source, encoding="utf-8")

def main() -> None:
    gen_articles()
    gen_services()
    gen_corporate_pages()
    print(f"Generated {len(ARTICLES)} article pages, {len(SERVICES)} service pages and 7 company pages.")

if __name__ == "__main__":
    main()
